### ISSUE TITLE
Linking against openssl not allowed without special exception

### ISSUE THREAD

**Issue by simonft** [xray7224/PyPump#101]
pypump links against openssl, but openssl's license is not compatible with the GPL-3. You can add the following exception to the GPL to make it compatible:

<blockquote>
 In addition, as a special exception, the copyright holders give
 permission to link the code of portions of this program with the
 OpenSSL library under certain conditions as described in each
 individual source file, and distribute linked combinations
 including the two.
 You must obey the GNU General Public License in all respects
 for all of the code used other than OpenSSL.  If you modify
 file(s) with this exception, you may extend this exception to your
 version of the file(s), but you are not obligated to do so.  If you
 do not wish to do so, delete this exception statement from your
 version.  If you delete this exception statement from all source
 files in the program, then also delete it here.
</blockquote>

See here for more information:
https://people.gnome.org/~markmc/openssl-and-the-gpl.html

**Comment by MartinBorg** [comment]
I can't find anython newer than 0.3 in Debian.

**Comment by dper** [comment]
@Simonft The newest version of what?  In Sid (also experimental) PyPump is at 0.3.  https://packages.debian.org/sid/python-pypump

**Comment by moggers87** [comment]
I suggest filing a bug with debian then ;)

On January 7, 2015 1:09:30 AM GMT, MartinBorg <notifications@github.com> wrote:
>I can't find anython newer than 0.3 in Debian.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/xray7224/PyPump/issues/101#issuecomment-68963709

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MartinBorg** [comment]
There is Debian bug https://bugs.debian.org/740990

The question is: Does pypump still link against openssl and if so does the license reflect this? Correct me if I'm wrong, but the issue seems to be still unsolved and should be reopened.

**Comment by moggers87** [comment]
As stated above, OpenSSL is a system library (the system in this case being Python, PyPump doesn't interact directly with the OS).

**Comment by moggers87** [comment]
Having read the Debian bug now (was on my phone), I think you might be been referring to python-openssl - that is an optional library that can be useful for things like SNI support on Python 2.x.

This is entirely an issue for distributions as PyPump doesn't depend on python-openssl and the GPL only comes into force upon *distribution*. 

I hope that makes things clearer.

**Comment by MartinBorg** [comment]
The problem is: As soon as GPLed Python code imports the requests library, you have the program linked against the OpenSSL library:

```python
#!/usr/bin/python3

__license__ = "GPL-3+ w/o OpenSSL exception"

import os
import subprocess

import requests

if __name__ == "__main__":
    lsof = subprocess.Popen(["lsof", "-p", str(os.getpid())],
                            stdout=subprocess.PIPE)
    out, _ = lsof.communicate()
    for s in out.decode().split("\n"):
        if "/libssl.so." in s:
            print(s)
```

Because OpenSSL is not a system library, this work cannot be distributed, not by Debian nor anyone else.

Is there any reason to not add the OpenSSL exception clause to the license? Other than, of course, it is some work and all copyright holders have to agree.

The discussion is still ongoing in Debian (debian-legal@lists.debian.org).

**Comment by moggers87** [comment]
> Because OpenSSL is not a system library

That's clearly where we disagree. I define the "system" as Python, therefore anything used to implement the standard library is a "system library" IMO.

As I understand it, none of the other copyright holders believe it is necessary to give an exception and at least one is opposed to doing so.

**Comment by MartinBorg** [comment]
In my personal opinion, there is indeed no license problem, because because users can expect that both Python and OpenSSL are installed on a typical Debian system. But at least some people in Debian seem to disagree. To calm down those sceptics, the exception would be helpful. What I did not understand so far: What is the reason to oppose the exception? Is there any drawback? Other than have pypump in Debian :~)

**Comment by moggers87** [comment]
> What I did not understand so far: What is the reason to oppose the exception? Is there any drawback?

@xray7224 doesn't like it because OpenSSL's license is GPL-incompatible. A linking exception would allow a derivative work that includes packages such as PyOpenSSL - this goes beyond reaffirming rights that distributions already have.

I'm going to lock the thread now as it's quite clear this is a Debian internal issue.

**Comment by moggers87** [comment]
Just to reiterate one final time, in case any of the above was not clear:

OpenSSL is only considered a system library where it is being used to provide features that are part of the Python standard library.
